### ISSUE TITLE
Add argument for selecting which fisheries to plot with plot.selectivity()

### ISSUE THREAD

**Issue by drfinlayscott** [PacificCommunity/ofp-sam-diags4MFCL#13]
Subset by fishery number. So we can subset out certain fisheries, e.g. purse seine (if we know what numbers they are).
Default is to plot all fisheries.

**Comment by mtvincent-NOAA** [comment]
We could also add in the option to just feed it a list of par files of the same length or a single par file and get the groupings from fish flag 24 and only plot the first of each group

**Comment by N-DucharmeBarth** [comment]
I think my preference would be to pass an index of which fisheries to plot. I don't want to have to pass multiple objects MFCL objects to a single function if I don't have to. Also, if you go with an index of fisheries then it is less likely to break if you are comparing models with different fishery structures.

If people are reasonably happy with that I'll go ahead and make that change. I've got some models running so I was going to take this morning to build-out some of the functionality of a few of the plots anyways.

**Comment by mtvincent-NOAA** [comment]
I guess it becomes a question of whether you are expecting that all of the models will have the same fisheries, If you have different fisheries for whatever reason then you would probably want to be able to send it a different vector for each model ? I think this might be rare and could probably just go with sending it a single vector?

I'm also waiting for models today and am working on the plot maturity function.
